name: Secrets workflow

on:
  pull_request:
    branches: ["main"]

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

permissions:
  contents: read

jobs:
  build:
    name: Secrets
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:
      - name: echo environment variable
        run: echo "The value of $JOB_NAME is $API_CSPROJ_PATH"
