name: Secrets workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: dotnet format
        run: dotnet format -v detailed --verify-no-changes
