name: "Step - deploy"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      app_name:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

env:
  resource_group_name: rg-${{ inputs.app_name }}-${{inputs.environment}}

jobs:
  deploy:
    name: Deploy ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            infrastructure

      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Bicep
        run: |
          az deployment group create \
              --name ${{ inputs.environment }}-deployment-${{ github.run_number }} \
              --template-file infrastructure/main.bicep \
              --resource-group ${{ env.resource_group_name }} \
              --parameters appName=${{ inputs.app_name }} environment=${{ inputs.environment }}  \
              --verbose

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-${{ inputs.app_name }}-${{ inputs.environment }}
          package: artifacts/
